### PR TITLE
fix: resolve issues and refactor

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Issue Number: #69 #70 #72 

## What is the new behavior?
Properties can be accessed

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by splincode** [comment]
where test when you use auto bind?

```ts
  @Dispatch()
  public setAppInformation() {
    this.api.getInformation().pipe(
      switchMap(({ version }) => this.api.getSchemaForVersion(version)),
      map(({ schema }) => new SetAppSchema(schema))
    );
  }
```
instead
```ts
  @Dispatch()
  public setAppInformation = () =>
    this.api.getInformation().pipe(
      switchMap(({ version }) => this.api.getSchemaForVersion(version)),
      map(({ schema }) => new SetAppSchema(schema))
   );
```

**Comment by arturovt** [comment]
What is "auto bind"? There is any description in that issue and it's linked with #72

**Comment by splincode** [comment]
when I use methods without lambda syntax

```ts
@Dispatch()
  public setAppInformation() {
    this.api.getInformation().pipe(
      switchMap(({ version }) => this.api.getSchemaForVersion(version)),
      map(({ schema }) => new SetAppSchema(schema))
    );
  }
```

 this - is correct works?

**Comment by arturovt** [comment]
You are not returning anything, this won't work.

**Comment by arturovt** [comment]
https://github.com/ngxs-labs/dispatch-decorator/blob/007ba80dec98ad6307a245e962daccef903eb2b9/src/tests/dispatch.spec.ts#L282

**Comment by splincode** [comment]
> it('should be possible to access instance properties', (done: jest.Don

good)

**Comment by arturovt** [comment]
Should the next version be `1.3.0` or `2`?

**Pull request merged**
